<?xml version="1.0"?>
<package format="3">
  <name>avs_pdbackstepingcontrol</name>
  <version>0.0.1</version>
  <description>PD-Backstepping lane-following cmd_vel controller for AVS Raspberry Pi 5 robot car.</description>

  <maintainer email="avs@example.com">avs</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
